export default  {
  POPUP_GLOBAL: (state) => state.global,
  POPUP_LOCAL: (state) => state.localModal,
  POPUP_AVATAR: (state) => state.avatarModal,
  POPUP_LANG: (state) => state.lang,
  POPUP_CONTACTS: (state) => state.contacts,
  POPUP_SUPPORT: (state) => state.support,
  POPUP_THANK: (state) => state.thank,
  POPUP_ERROR: (state) => state.error,
  POPUP_LOGIN: (state) => state.LOGIN,
  POPUP_CONFIRM: (state) => state.confirm,
  POPUP_COOKIE: (state) => state.cookie,
  POPUP_COMING_SOON: (state) => state.comingSoon,
  POPUP_NOT_FOUND: (state) => state.notFound,
  POPUP_USER_ADS: (state) => state.userAds,
}
