export default  {
  OPEN_PAGE: (state) => state.openPage,
  GET_PRODUCTS: (state) => state.getProducts,
  PRODUCTS: (state) => state.products,
  TOP_PRODUCTS: (state) => state.top_products,
  PRODUCTS_TOTAL_PAGE: (state) => +state.total,
  PRODUCTS_PAGE: (state) => +state.page,
  SORT: (state) => state.sort,
  PRODUCTS_LOADING: (state) => state.productsLoading,
  SEARCH: (state) => state.search,
  CITY: (state) => state.city,
  CITY_SEARCH: (state) => state.citySearch,
  SEARCH_TEXT: (state) => state.searchText,
  MILS: (state) => state.mils,
  MIL: (state) => state.mil,
  COST_TO: (state) => state.costTo,
  COST_FROM: (state) => state.costFrom,
  SEARCH_ANSWERS_IDS: (state) => state.answersIds,
  SEARCH_ANSWERS_FILTERS_IDS: (state) => state.answersFiltersIds,
  SEARCH_CATEGORY: (state) => state.category,
}
