name: DEV Deploy and Build on Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to remote server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_DEV_HOST }}
        username: ${{ secrets.SERVER_DEV_USER }}
        password: ${{ secrets.SSH_DEV_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        source: "."
        target: "/home/apps/frontend"

    - name: SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_DEV_HOST }}
        username: ${{ secrets.SERVER_DEV_USER }}
        password: ${{ secrets.SSH_DEV_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /home/apps/frontend
          npm i
          pm2 stop frontend
          npm run build
          pm2 start frontend
