name: PROD Deploy and Build on Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to remote server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        source: "."
        target: "/home/apps/frontend"

    - name: SSH commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /home/apps/frontend
          sudo chown -R root:root .
          npm i
          pm2 stop frontend
          npm run build
          pm2 start frontend
